### ISSUE TITLE
oauth problems with latest bits

### ISSUE THREAD

**Issue by pgdh** [yangl1996/nesthub#1]
I'm using your latest bits, Ubuntu 20.04.2 LTS and go1.15.8

I had a bit of "fun" setting up (I had to add the localhost:7979 URrIL in two places (Authorized JavaScript origins, and Authorized redirect URIs).

$ ./nesthub -setup
Please open https://nestservices.google.com/partnerconnections/7fxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx06/auth?redirect_uri=http://localhost:7979&access_type=offline&prompt=consent&client_id=98xxxxxxxx43-gdxxxxxxxxxxxxxxxxxxxxxxxxxxxxh9.apps.googleusercontent.com&response_type=code&scope=https://www.googleapis.com/auth/sdm.service in browser
2021/02/06 01:57:28 Authorization successful.
2021/02/06 01:57:28 oauth2: cannot fetch token: 400 Bad Request
Response: {
  "error": "invalid_request",
  "error_description": "Missing required parameter: code"
}

The redirect was ...

http://localhost:7979/code=4/0AxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxmA&scope=https:/www.googleapis.com/auth/sdm.service

**Comment by nateinaction** [comment]
Thanks for this. I ran the setup on MacOS and only needed to add the redirect to Authorized redirect URIs. I'll be setting this up on a linux distro shortly and should be able to see that setup flow.

**Comment by nateinaction** [comment]
Sorry for the late reply. I've tried the setup with the latest release `v1.2.1` on NixOS 22.05 and haven't had any issues.
```
nesthub -setup
2022/08/25 01:40:54 Enabling Smart Device Management API
2022/08/25 01:40:56 Waiting for the Smart Device Management API to be enabled...
Please open https://nestservices.google.com/partnerconnections/ba...8c/auth?redirect_uri=http://localhost:7979&access_type=offline&prompt=consent&client_id=36...kc.apps.googleusercontent.com&response_type=code&scope=https://www.googleapis.com/auth/sdm.service in browser
2022/08/25 01:41:16 Authorization successful. 4/...lw
...
```

Closing. Please let me know if you're still running into issues.
